version: '3'
services:
  node:
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/usr/src/app
    command: npm start
    networks:
      - common
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - common
networks:
  common:
volumes:
  mongodb: