version: '3'
services:
  node:
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/usr/src/app
    command: npm start
    networks:
      - common
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - common
  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    ports:
      - 6379:6379
    networks:
      - common
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    restart: unless-stopped
networks:
  common:
volumes:
  mongodb: