const ExpressApp = require('../singleton/Express')
const path = require('path')
const SiteRouter = require('./site.router')
const AdminRouter = require('./admin.router')
const ApiRouter = require('./api.router')
const router = ExpressApp.getInstance()

router.use('/api/v1', ApiRouter)
router.use('/admin', AdminRouter)
router.use('/', SiteRouter)
